@startuml
'https://plantuml.com/sequence-diagram

interface MyTokenizer {
    + tokenize(): List<String>
}

MyTokenizer <|.. TachTu
MyTokenizer <|.. TokenizeDecorator
TokenizeDecorator o--> MyTokenizer : token
TokenizeDecorator <|.. LoaiBoTuDung
TokenizeDecorator <|.. LoaiBoDauCau
@enduml
